-- Seed insurance_companies with major Swiss insurance companies
-- The table was empty, causing the "Compagnie" dropdown to be empty in Référentiel > Nouveau produit

INSERT INTO insurance_companies (name) VALUES
  ('AXA'),
  ('Zurich'),
  ('Helvetia'),
  ('La Mobilière'),
  ('Vaudoise'),
  ('Generali'),
  ('Allianz'),
  ('Baloise'),
  ('CSS'),
  ('Swica'),
  ('Helsana'),
  ('Sanitas'),
  ('Groupe Mutuel'),
  ('Concordia'),
  ('Visana'),
  ('Sympany'),
  ('Assura'),
  ('ÖKK'),
  ('Atupri'),
  ('KPT'),
  ('EGK'),
  ('Agrisano'),
  ('Nationale Suisse'),
  ('Smile'),
  ('Emmental'),
  ('Swiss Life'),
  ('PAX'),
  ('Retraites Populaires'),
  ('TCS'),
  ('Coop Protection Juridique'),
  ('DAS Protection Juridique'),
  ('CAP Protection Juridique'),
  ('Elvia'),
  ('ERV'),
  ('Innova'),
  ('Liberty'),
  ('Orion'),
  ('Phenix'),
  ('Protekta')
ON CONFLICT (name) DO NOTHING;
