-- ============================================================================
-- ❌ ANNULÉE — NE PAS APPLIQUER
-- ============================================================================
-- Cette migration a été annulée le 12 juin 2026 après revue par Habib.
--
-- Le contenu original proposait une policy SELECT
-- `"RETURNING-safe tenant member view"` USING `user_is_member_of_tenant`
-- qui autorisait TOUT membre tenant à SELECT * sur tous les clients du
-- tenant. CE FIX CASSAIT LE SCOPE PAR RÔLE :
--   - Agent qui n'aurait dû voir QUE ses clients assignés
--   - Manager qui n'aurait dû voir QUE son équipe
-- → Régression sécurité non acceptable.
--
-- Le vrai bug est probablement dans `has_global_scope_v2()` qui retourne
-- `false` pour les Admin Cabinet créés via `tenant-onboarding` parce
-- qu'ils n'ont pas systématiquement un `tenant_role` avec
-- `dashboard_scope='global'` + permission `clients.view`.
--
-- Plan corrigé :
--   1. Migration diagnostic ciblé `20260612232000_diagnose_v1_scopes.sql`
--      qui dump le tenant_role + permissions de chaque Admin Cabinet
--      actif pour identifier qui est mal provisionné.
--   2. Selon résultat :
--      - Fix A : élargir `user_has_global_client_scope()` pour reconnaître
--        un flag UTA explicite (ex `uta.is_tenant_admin = true`).
--      - Fix B : corriger `tenant-onboarding` + migration de backfill.
--
-- Cette migration reste dans le repo en mode no-op pour traçabilité
-- (l'analyse avait au moins identifié le bon mécanisme RETURNING).
-- ============================================================================

-- NO-OP : aucune opération SQL exécutée.
-- (Postgres accepte un fichier de migration avec juste des commentaires.)
SELECT 1 WHERE false;
